### ISSUE TITLE
Investigate caching

### ISSUE THREAD

**Issue by armanbilge** [typelevel/download-java#9]

**Comment by armanbilge** [comment]
The readme for [setup-java](https://github.com/actions/setup-java) says it supports
> Extracting and caching custom version of Java from a local file

So maybe we already have caching?

**Comment by armanbilge** [comment]
I forgot, another question was if we even want to cache and if so what the cache key should be.

One approach would be instead of referencing the `main` branch of jdk-index, we could reference a specific hash (which would then be the cache key). Then, every time jdk-index updates we'd release a new version of this action.

This is only viable with automation. Is it worth it?

**Comment by vasilmkd** [comment]
Is it possible to obtain the latest hash instead of referring to it by the branch name?

**Comment by armanbilge** [comment]
We could probably call the GH API (or something similar) to get that information. That's a good idea actually.

**Comment by armanbilge** [comment]
The other one this doesn't help us with is temurin since the download URL is always "latest" right?

**Comment by vasilmkd** [comment]
I could in theory find a specific url for those too. I haven't looked hard enough.

**Comment by armanbilge** [comment]
Their page says to use GH for versioned URLs.
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html#versioned-downloads

**Comment by vasilmkd** [comment]
Awesome, I'll switch the index to that then.
